### ISSUE TITLE
Closing dropdown on re-clicking the toggle

### ISSUE THREAD

**Issue by YifanM** [pleerock/ng2-dropdown#2]
This isn't really an issue, but it would be nice if you could add that. I tried myself but the files from the npm install only have the structure unlike these files in your github (I don't know what's happening)? Thanks, your code is helpful nonetheless.

**Comment by pleerock** [comment]
I think I can add it

**Comment by pleerock** [comment]
fixed in 27e2488..f265557, released in 0.0.7

**Comment by pleerock** [comment]
and yeah, don't forget to star it, if you liked it ;)

**Comment by YifanM** [comment]
Are there any extra steps to use it with the new version? I tried reinstalling it with npm, but it didn't seem like it updated. I tried adding the new [dropdownToggle] but it didn't recognize it. 

And yeah, thanks a lot for the quick update, you definitely deserved my star. I spent so long trying to make my own dropdown...

**Comment by pleerock** [comment]
no you should not do anything - its working without any additional changes. Try to copy/paste code in the sample in README. That code totally is working for me

**Comment by YifanM** [comment]
Okay you're right, it's working for me now after I tried installing on a different machine. I don't know why that happened.

Thanks a lot for the dropdown!

**Comment by pleerock** [comment]
found one issue and fixed it in eb7ed23 released 0.0.9 - maybe you had same issue
