### ISSUE TITLE
Menu closes before element click is triggered

### ISSUE THREAD

**Issue by Sjiep** [pleerock/ng2-dropdown#3]
When I open the dropdown menu and try to click on an anchor element inside the dropdown list. The menu closes before the anchor click is 'registered'. 

Take the following code and try to click on Badman. You would expect to go to google, however the dropdown menu just collapses. It seems that the menu is closes before the click on the menu is triggered?

```
<!-- button dropdown -->
    <div class="dropdown" dropdown>
        <button dropdown-open>My Heroes</button>
        <ul class="dropdown-menu">
            <li><a href="http://www.google.com">Badman</a></li>
        </ul>
    </div>
```

A workaround would be to add `dropdown-not-closable-zone` to `<ul>` of the menu. As long as you navigate to a different screen, you won't notice the menu stays open and the clicks on the link is registered.

Any idea how to solve this?

**Comment by pleerock** [comment]
fixed in the latest version

**Comment by Sjiep** [comment]
Works, thanks!
